### ISSUE TITLE
XSS対策

### ISSUE THREAD

**Issue by hiromundo** [hiromundo/lamp_practice#4]

**Comment by Tigerstyle88** [comment]
Hello , some may know me and some may not ! 7 months ago I would never thought I’d be so In love , maybe natural cus I’m a bench jeweler and create with my hands but I love it and I can also put my other training in place ! So any Python guys out there , I’m a student! Also I was going to start a fund raisers once I know people on here to help manage it but I’d like to buy as many raspberry pi zero w and approval from a elementary school I could show these kids how to hook up the hardware , nice to talk
